// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deleteFeedFollowByIds.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteFeedFollowByIds = `-- name: DeleteFeedFollowByIds :exec
DELETE FROM feed_follows WHERE user_id = $1 AND feed_id = $2
`

type DeleteFeedFollowByIdsParams struct {
	UserID uuid.UUID
	FeedID uuid.UUID
}

func (q *Queries) DeleteFeedFollowByIds(ctx context.Context, arg DeleteFeedFollowByIdsParams) error {
	_, err := q.db.ExecContext(ctx, deleteFeedFollowByIds, arg.UserID, arg.FeedID)
	return err
}
